genome:
  ploidy: 1
  heterozygosity: 0.5 # Probability that any given copy carries the variant

variants:

  DEL:
    count: 0        
    distribution: "pareto"
    parameters:
      median_length: 5000      # Target median length in bp
      sigma:             # standard deviation for the normal distribution
      min_length: 50        # minimum length of the variant
      max_length: 100000     # maximum length of the variant

  INS:
    count: 0
    distribution: "normal" 
    parameters:
      median_length: 10000
      sigma: 
      min_length: 50
      max_length: 100000


  DUP:                                # tandem duplications
    count: 0               
    distribution: "normal"
    parameters:
      median_length: 2000
      sigma: 200
      min_length: 50
      max_length: 5000
    copy_number:           
      min: 2
      max: 5
      weights: [0.7, 0.2, 0.05, 0.05] # Probability for CN=2, 3, 4, 5


  INV:
    count: 0
    distribution: "pareto"   
    parameters:
      median_length: 50000
      sigma: 1000
      min_length: 1000
      max_length: 100000

  # Copy & Paste traslocations / Interspersed Duplications
  TRA_COPY:
    count: 1000
    distribution: "pareto"   
    parameters:
      median_length: 50000
      sigma: 1000
      min_length: 1000
      max_length: 100000

  # Cut & Paste traslocations
  TRA_CUT:
    count: 1000
    distribution: "pareto"   
    parameters:
      median_length: 50000
      sigma: 1000
      min_length: 1000
      max_length: 100000
